version: '3.8'

services:
  backend:
    image: auto24-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - auto24-network
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - auto24-network

networks:
  auto24-network:
    driver: bridge
