import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./components/topbar";
import Header from "./components/header";
import Kuuluta from "./components/kuuluta";
import Foobar from "./components/foobar";
import Logo from "./components/logo";
import Sublogos from "./components/sublogos";
import React from "react";
import Banner from "@/app/components/banner";
import FooterSection from "@/app/components/footersection";
import { AuthUserProvider } from "@/app/context/AuthUserContext";
import AuthWrapper from "@/app/components/AuthWrapper"; // Import AuthWrapper

export const metadata: Metadata = {
    title: "Avaleht - auto24.ee",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className="display flex flex-col">
        <AuthUserProvider>
            <AuthWrapper>
                <Header className="w-full hidden md:block" />
                <div className="mx-auto flex flex-col w-full max-w-custom">
                    <div>
                        <Banner className="hidden lg:block" />
                        <div className="flex items-center w-full">
                            <Logo className="flex-grow logo-details overall-margin-left mr-4" />
                            <Sublogos />
                        </div>
                        <TopBar />
                        <Kuuluta />
                        <div className="w-[1000px] overall-margin-left">
                            {children}
                        </div>
                    </div>
                </div>
                <Foobar />
                <FooterSection />
            </AuthWrapper>
        </AuthUserProvider>
        </body>
        </html>
    );
}
