import type { Metadata } from "next";
import "./globals.css";
import TopBar from "./components/topbar";
import Header from "./components/header";
import Kuuluta from "./components/kuuluta";
import Logo from "./components/logo";
import Sublogos from "./components/sublogos";
import React from "react";
import Banner from "@/app/components/banner";

export const metadata: Metadata = {
    title: "Avaleht - auto24.ee",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="display flex flex-col">
        <Header className="w-full hidden md:block"></Header>
        <div className="mx-auto flex flex-col w-full max-w-custom">
            <div>
                <Banner className="hidden md:block"></Banner>
                <div className="flex items-center w-full ">
                    <Logo className="flex-grow logo-details overall-margin-left mr-4"></Logo>
                    <Sublogos></Sublogos>
                </div>
                <TopBar></TopBar>
                <Kuuluta></Kuuluta >
                <div className=" w-[1000px] overall-margin-left">
                    {children}
                </div>
            </div>
        </div>
        </body>
        </html>
    );
}