const featureLabels = {
    safetyAndSecurity: {
        powerSteering: 'Power Steering',
        centralLocking: 'Central Locking',
        absBrakes: 'ABS Brakes',
        electronicParkingBrake: 'Electronic Parking Brake',
        airbag: 'Airbag',
        curtainAirbags: 'Curtain Airbags',
        passengerAirbagDeactivation: 'Passenger Airbag Deactivation',
        driverFatigueDetection: 'Driver Fatigue Detection',
        alarm: 'Alarm',
        immobilizer: 'Immobilizer',
        stabilityControl: 'Stability Control',
        brakeForceControl: 'Brake Force Control',
        tractionControl: 'Traction Control',
        laneKeepingAssist: 'Lane Keeping Assist',
        laneChangeAssist: 'Lane Change Assist',
        trafficSignRecognition: 'Traffic Sign Recognition',
        nightVisionAssist: 'Night Vision Assist',
        blindSpotWarning: 'Blind Spot Warning',
        collisionPreventionBrake: 'Collision Prevention Brake',
        pedestrianSafetyHood: 'Pedestrian Safety Hood',
        automaticBrakingSystem: 'Automatic Braking System',
        additionalBrakeLight: 'Additional Brake Light',
        rainSensor: 'Rain Sensor',
        isofix: 'Isofix',
        integratedChildSeat: 'Integrated Child Seat',
        seatbeltPretensioners: 'Seatbelt Pretensioners',
        autoHold: 'Auto Hold',
        hillBrake: 'Hill Brake',
    },
    lights: {
        xenon: 'Xenon',
        laser: 'Laser',
        led: 'LED',
        headlightWashers: 'Headlight Washers',
        corneringLights: 'Cornering Lights',
        daytimeRunningLights: 'Daytime Running Lights',
        highBeamAssist: 'High Beam Assist',
        fogLights: 'Fog Lights',
        headlightLeveling: 'Headlight Leveling',
        additionalLights: 'Additional Lights',
        lightingPackage: 'Lighting Package',
    },
    tiresAndWheels: {
        summerTires: 'Summer Tires',
        winterTires: 'Winter Tires',
        alloyWheels: 'Alloy Wheels',
        hubcaps: 'Hubcaps',
        spareTire: 'Spare Tire',
        tirePressureMonitoring: 'Tire Pressure Monitoring',
        summerTiresIncluded: 'Summer Tires Included',
        winterTiresIncluded: 'Winter Tires Included',
        alloyWheelsIncluded: 'Alloy Wheels Included',
        hubcapsIncluded: 'Hubcaps Included',
    },
    steering: {
        adjustableSteeringColumn: 'Adjustable Steering Column',
        multifunctionSteeringWheel: 'Multifunction Steering Wheel',
        leatherSteeringWheel: 'Leather Steering Wheel',
        sportSteeringWheel: 'Sport Steering Wheel',
        heatedSteeringWheel: 'Heated Steering Wheel',
        paddleShifters: 'Paddle Shifters',
        rightHandDrive: 'Right Hand Drive',
    },
    seats: {
        leatherUpholstery: 'Leather Upholstery',
        partialLeatherUpholstery: 'Partial Leather Upholstery',
        velourUpholstery: 'Velour Upholstery',
        textileUpholstery: 'Textile Upholstery',
        electricallyAdjustableSeats: 'Electrically Adjustable Seats',
        airAdjustableSeat: 'Air Adjustable Seat',
        heightAdjustableSeats: 'Height Adjustable Seats',
        seatHeaters: 'Seat Heaters',
        adjustableLumbarSupport: 'Adjustable Lumbar Support',
        massageSeats: 'Massage Seats',
        ventilatedSeats: 'Ventilated Seats',
        frontArmrest: 'Front Armrest',
        rearArmrest: 'Rear Armrest',
        foldingPassengerSeatBackrest: 'Folding Passenger Seat Backrest',
        foldingRearSeatBackrest: 'Folding Rear Seat Backrest',
        comfortSeats: 'Comfort Seats',
        sportSeats: 'Sport Seats',
    },
    comfortFeatures: {
        climateControl: 'Climate Control',
        electricExteriorMirrors: 'Electric Exterior Mirrors',
        virtualExteriorMirrors: 'Virtual Exterior Mirrors',
        virtualInteriorMirror: 'Virtual Interior Mirror',
        electricWindowLifters: 'Electric Window Lifters',
        tintedWindows: 'Tinted Windows',
        sunroof: 'Sunroof',
        panoramicRoof: 'Panoramic Roof',
        doorServoClosers: 'Door Servo Closers',
        keylessEntry: 'Keyless Entry',
        keylessStart: 'Keyless Start',
        cruiseControl: 'Cruise Control',
        electricTrunkOpening: 'Electric Trunk Opening',
        mirrorsInSunVisors: 'Mirrors in Sun Visors',
        rearWindowSunblind: 'Rear Window Sunblind',
        doorSunblinds: 'Door Sunblinds',
        enginePreheater: 'Engine Preheater',
        cabinPreheater: 'Cabin Preheater',
        additionalCabinHeater: 'Additional Cabin Heater',
        integratedGarageOpener: 'Integrated Garage Opener',
        autoDimmingMirrors: 'Auto Dimming Mirrors',
        rearSeatClimateControl: 'Rear Seat Climate Control',
        doorInteriorLighting: 'Door Interior Lighting',
        readingLights: 'Reading Lights',
        parkingSensors: 'Parking Sensors',
        parkingCamera: 'Parking Camera',
        automaticParking: 'Automatic Parking',
        comingLeavingHomeFunction: 'Coming/Leaving Home Function',
        digitalInstrumentPanel: 'Digital Instrument Panel',
        headUpDisplay: 'Head-Up Display',
        trunkSlidingFloor: 'Trunk Sliding Floor',
        electricSlidingDoors: 'Electric Sliding Doors',
        wirelessPhoneCharging: 'Wireless Phone Charging',
    },
    additionalFeatures: {
        adjustableSuspension: 'Adjustable Suspension',
        airSuspension: 'Air Suspension',
        startStopSystem: 'Start-Stop System',
        powerSockets12V: '12V Power Sockets',
        roofRails: 'Roof Rails',
        skiBag: 'Ski Bag',
        tireRepairKit: 'Tire Repair Kit',
        cooledGloveBox: 'Cooled Glove Box',
        outsideTemperatureGauge: 'Outside Temperature Gauge',
        doubleGlazedWindows: 'Double Glazed Windows',
        heatedWindshield: 'Heated Windshield',
        rearWindowHeating: 'Rear Window Heating',
        washerNozzleHeating: 'Washer Nozzle Heating',
        luggageCover: 'Luggage Cover',
        cargoNet: 'Cargo Net',
        separationNet: 'Separation Net',
        cargoTieDownHooks: 'Cargo Tie-Down Hooks',
        rearWiper: 'Rear Wiper',
        fireExtinguisher: 'Fire Extinguisher',
        towHitch: 'Tow Hitch',
        trailerStabilityAssist: 'Trailer Stability Assist',
        tripComputer: 'Trip Computer',
        mudFlaps: 'Mud Flaps',
        accessibilityEquipment: 'Accessibility Equipment',
        fourWheelSteering: 'Four-Wheel Steering',
    }

};

export default featureLabels;
