const CarDetailsFormData = {
    phone: '',
    name: 'Enar Leini',
    email: 'enar.leini00@gmail.com',
    vehicleType: '',
    bodyType: '',
    bodyTypeDetail: '',
    brand: '', // `make` in DTO
    model: '',
    modelGeneration: '',
    modelTrim: '',
    firstRegistrationDate: '',
    price: '',
    includesRegistrationFee: false,
    mileage: '',
    hasServiceBook: false,
    vinCode: '',
    registrationNumber: '',
    transmission: '',
    driveType: '',
    engineCapacityLiters: '',
    engineCapacityCubicCentimeters: '',
    engineConfiguration: '',
    engineDetails: '',
    enginePowerKW: '',
    enginePowerHP: '',
    fuelType: '',
    fuelTankCapacity: '',
    fuelConsumptionHighway: '',
    fuelConsumptionCity: '',
    fuelConsumptionCombined: '',
    fuelConsumptionStandard: '',
    co2Emissions: '',
    seatingCapacity: '',
    numberOfDoors: '',
    hasWarranty: false,
    isAccidentDamaged: false, // `accidentDamaged` in DTO
    color: '',
    isMetallicColor: false, // `metallicColor` in DTO
    colorDetail: '',
    curbWeight: '',
    grossWeight: '',
    payloadCapacity: '',
    brakedTrailerWeight: '',
    unbrakedTrailerWeight: '',
    wheelbase: '',
    length: '',
    width: '',
    height: '',
    acceleration0To100: '',
    topSpeed: '',
    locationCountry: 'Eesti',
    locationCounty: '',
    importedFromCountry: '',
    registeredInCountry: false,
    inspectionValidUntil: '',
    isReserved: false, // `reserved` in DTO
    reservationUntilDate: '',
    exchangePossible: false,
    exchangeDetails: '',
    description: '',
};

export default CarDetailsFormData;