import {CarExtraInfoDTO} from "@/app/types/types";

const CarExtraInfoFormData:CarExtraInfoDTO={
    safetyAndSecurity:{
        powerSteering: false,
        centralLocking: false,
        absBrakes: false,
        electronicParkingBrake: false,
        airbag: false,
        curtainAirbags: false,
        passengerAirbagDeactivation: false,
        driverFatigueDetection: false,
        alarm: false,
        immobilizer: false,
        stabilityControl: false,
        brakeForceControl: false,
        tractionControl: false,
        laneKeepingAssist: false,
        laneChangeAssist: false,
        trafficSignRecognition: false,
        nightVisionAssist: false,
        blindSpotWarning: false,
        collisionPreventionBrake: false,
        pedestrianSafetyHood: false,
        automaticBrakingSystem: false,
        additionalBrakeLight: false,
        rainSensor: false,
        isofix: false,
        integratedChildSeat: false,
        seatbeltPretensioners: false,
        autoHold: false,
        hillBrake: false
    },
    lights:{
        xenon: false,
        laser: false,
        led: false,
        headlightWashers: false,
        corneringLights: false,
        daytimeRunningLights: false,
        highBeamAssist: false,
        fogLights: false,
        headlightLeveling: false,
        additionalLights: false,
        lightingPackage: false
    },
    tiresAndWheels: {
        summerTires: false,
        winterTires: false,
        alloyWheels: false,
        hubcaps: false,
        spareTire: false,
        tirePressureMonitoring: false,
        summerTiresIncluded: false,
        winterTiresIncluded: false,
        alloyWheelsIncluded: false,
        hubcapsIncluded: false
    },
    steering: {
        adjustableSteeringColumn: false,
        multifunctionSteeringWheel: false,
        leatherSteeringWheel: false,
        sportSteeringWheel: false,
        heatedSteeringWheel: false,
        paddleShifters: false,
        rightHandDrive: false
    },
    seats: {
        leatherUpholstery: false,
        partialLeatherUpholstery: false,
        velourUpholstery: false,
        textileUpholstery: false,
        electricallyAdjustableSeats: false,
        airAdjustableSeat: false,
        heightAdjustableSeats: false,
        seatHeaters: false,
        adjustableLumbarSupport: false,
        massageSeats: false,
        ventilatedSeats: false,
        frontArmrest: false,
        rearArmrest: false,
        foldingPassengerSeatBackrest: false,
        foldingRearSeatBackrest: false,
        comfortSeats: false,
        sportSeats: false
    },
    comfortFeatures: {
        climateControl: false,
        electricExteriorMirrors: false,
        virtualExteriorMirrors: false,
        virtualInteriorMirror: false,
        electricWindowLifters: false,
        tintedWindows: false,
        sunroof: false,
        panoramicRoof: false,
        doorServoClosers: false,
        keylessEntry: false,
        keylessStart: false,
        cruiseControl: false,
        electricTrunkOpening: false,
        mirrorsInSunVisors: false,
        rearWindowSunblind: false,
        doorSunblinds: false,
        enginePreheater: false,
        cabinPreheater: false,
        additionalCabinHeater: false,
        integratedGarageOpener: false,
        autoDimmingMirrors: false,
        rearSeatClimateControl: false,
        doorInteriorLighting: false,
        readingLights: false,
        parkingSensors: false,
        parkingCamera: false,
        automaticParking: false,
        comingLeavingHomeFunction: false,
        digitalInstrumentPanel: false,
        headUpDisplay: false,
        trunkSlidingFloor: false,
        electricSlidingDoors: false,
        wirelessPhoneCharging: false
    }




}
export default CarExtraInfoFormData